spring:
  datasource:
    url: jdbc:mysql://rdsstudyemploy.c7gmus2cs4zw.ap-southeast-2.rds.amazonaws.com:3306
    username: admin
    password: LJmc1X8q0Ck5M32xBrLh
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 80