spring:
  datasource:
    url: ${mysql.url}
    username: ${mysql.user}
    password: ${mysql.password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
