spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: mysqlmysql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
server:
  port: 8888